### ISSUE TITLE
ic2 -> bc conversion not working

### ISSUE THREAD

**Issue by fusionmc-evilscoop** [zerotheliger/PowerConverters#11]
ic2 experimental build 306
BC 4.1.2
Forge 953

Trying with HV and MV consumer, no output at BC producer.
Wooden kenisis or any other kenisis pipe.

A lot of other mods loaded, I use a dns techpack base (current version with a few additions and a few removals) inc thermal expansion b7

**Comment by samrg472** [comment]
Fixed in build 29
