### ISSUE TITLE
[Crash] Still requires BuildCraft

### ISSUE THREAD

**Issue by thatsIch** [zerotheliger/PowerConverters#13]
http://pastebin.com/8Vw9Aax6

**Comment by samrg472** [comment]
Can you try starting Minecraft without PowerCrystalsCore (and yes, everything that depends on it too)?
It seems that core _might_ be the initial cause, but I'm not sure yet, since the core was mentioned in the log

```
at powercrystals.core.asm.PCCASMTransformer.transform(PCCASMTransformer.java:35)
```

**Comment by thatsIch** [comment]
Thank you, new version fixed it. And sorry I responded not fast enough.
