### ISSUE TITLE
Unable to connect any fluid or liquid transport to steam consumers or producers

### ISSUE THREAD

**Issue by Ravin3333** [zerotheliger/PowerConverters#4]
I tried to connect all forms of fluid and liquid pipes and tubes to both consumers and produces neither of which gave any connection. When viewed from within the energy bridge it simply said no connection, even placing a steam source next to a consumer would give no connection.

**Comment by samrg472** [comment]
This was fixed in commit 18355aa90237b04cc5a69b45e0fcb67e8feb340e
