### ISSUE TITLE
Unnable to  connect  BC Kinesis pipe to  BC Producer

### ISSUE THREAD

**Issue by Grossbaaffe** [zerotheliger/PowerConverters#6]
With BC4.1.0 ( I think the same appends withe BC4.0.x ) , minecraft 1.6.4,  and Powerconverter Build 19, BC Wooden kinesis pipe does not connect visually to BC producer. The BC producer face near the pipe become green, and the link is updated as expected in UI. But some power is drained from  the  energy  bridge,  and no power is transmited on pipe.

Energy is transmited as expeded to a machine directcly adjacent to BC producer.

**Comment by fndragon** [comment]
I had this problem with my fork.  To fix this, simply implement IPowerEmitter for the BC producer.  The wooden pipe looks specifically for that type class in order to connect.  My implementation of PowerConverters works with the BC 4.1 line.
