### ISSUE TITLE
With no BuildCraft installed you dont have access to the BuildCraft Producer/Provider

### ISSUE THREAD

**Issue by thatsIch** [zerotheliger/PowerConverters#8]
Even without Buildcraft there are a lot of mods out there who produce and use MJ. 
I am not sure if you can catch it but I think having access to the BC Producer/Provider and maybe calling it MJ Producer/Provider would be better.

**Comment by samrg472** [comment]
BuildCraft is required to be installed so the API is guaranteed to be available. Mods also fluctuate on API versions, therefore I only go by what BuildCraft distributes for minimal hassle.
